### ISSUE TITLE
"Event Type" - using "state_attr"

### ISSUE THREAD

**Issue by Jaeger1985a** [amaximus/anniversary#12]
I am trying to set up an anniversary list to coincide with our state and national holidays, which I have created as independent sensors using Calendarific. This way the holiday dates are always accurate, because it would pull the current information from the api that Cakenarific uses.

Here is the code I am trying to run, but the **sensor: sensor.holidays** does not contain any data:
 
  - platform: anniversary
    name: holidays
    multiple: true
    anniversaries:
      - event: '{{state_attr("binary_sensor.new_year_s_day2", "friendly_name")}}'
        date:  '{{state_attr("binary_sensor.new_year_s_day2", "date")}}'
        icon: mdi:part-popper

**Calendarific Created sensor attributes:**

date: '2022-01-01'
description: >-
  New Year's Day is the first day of the Gregorian calendar, which is widely
  used in many countries such as the USA.
attribution: Data provided by calendarific.com
unit_of_measurement: Days
friendly_name: New Year's Day
icon: mdi:calendar-blank

**Comment by amaximus** [comment]
Please note that the custom integration does not support jinja2 templating.
