### ISSUE TITLE
"type" attribute doesn't show up as an attribute of the sensor

### ISSUE THREAD

**Issue by dave-parsons** [amaximus/anniversary#14]
All my sensors are working but I can't get the "type" attribute to show up.   Below example.

```
      - event: 'Jack and Lizzy'
        date: '2016-07-16'
        icon: mdi:party-popper
        type: Anniversary


```

**Comment by amaximus** [comment]
Looking at the sensor in Developer Tools->States, do you see the type attribute for the event in the list of events?

![anniversaries](https://user-images.githubusercontent.com/2511168/163788966-baced91a-9a9e-4937-9996-2aebb9c0454e.png)

**Comment by amaximus** [comment]
Do you have any updates on this issue?
