### ISSUE TITLE
Multiple events not shown in custom button-card

### ISSUE THREAD

**Issue by jjvelar** [amaximus/anniversary#17]
Hi! Great idea! Thanks for creating this.

I have 0.2.2 version installed but I can't see in the button-card to events that will happen the same day.

That's what I have in configuration.yaml:

  - platform: anniversary
    name: anniversary_events
    anniversaries:
      - event: 'Inés y Anna'
        date: '2008-10-07'
        icon: mdi:cake-variant
      - event: 'Test-Test'
        date: '2008-10-07'     
        icon: mdi:cake-variant

And that's the custom button-card (it is the one you published as an example):

type: custom:button-card
size: 30px
styles:
  label:
    - font-size: 90%
  card:
    - height: 80px
  icon:
    - color: var(--paper-item-icon-color)
  grid:
    - position: relative
  custom_fields:
    notification:
      - background-color: |
          [[[
            if (states['sensor.anniversary_events'].state > 1)
              return "var(--light-primary-color)";
            return "var(--accent-color)";
          ]]]
      - border-radius: 50%
      - position: absolute
      - left: 62%
      - top: 10%
      - height: 20px
      - width: 20px
      - font-size: 9px
      - line-height: 20px
custom_fields:
  notification: |
    [[[ return states['sensor.anniversary_events'].state ]]]
label: |
  [[[
    var label = states['sensor.anniversary_events'].attributes.first_event_name
    return label.replace("|","<br>");
  ]]]
color_type: icon
show_label: true
show_name: false
entity: sensor.anniversary_events

Thanks in advance for your help.

**Comment by amaximus** [comment]
Please note that the Lovelace part is only an example, it's out of scope for thie repo.
For displaying multiple events you'll have to iterate over the events attribute (which is a sorted list) and display the needed events, e.g. either the first N events or the first upcoming event displaying several events if their event_in has the same value.
You'll have to play around the custom button card based on your needs.

An example for such an iteretion over an attribute can be found in my other repository: https://github.com/amaximus/met_alerts_hu
