### ISSUE TITLE
Two events on different start years, but the same month and day only the first one shows.

### ISSUE THREAD

**Issue by rdebrock91** [amaximus/anniversary#20]
I saw this was asked before and is closed now. (Was fixed) but i have this problem.

I have 2 persons birthday on the same day and month and different year  but it only shows 1 person at first_event_name.

How to fix this?

**Comment by rdebrock91** [comment]
`    - platform: anniversary
      name: events
      multiple: true
      anniversaries:
        - event: 'Person lastname1'
          date: '2002-12-14'
          icon: mdi:cake-variant
          type: birthday

        - event: 'Person lastname2'
          date: '1994-12-14'
          icon: mdi:cake-variant
          type: birthday`

This only shows "Person lastname1" in first event name.

**Comment by amaximus** [comment]
The integration used to have the `multiple` configuration parameter, but it became obsoleted as if there are many events on the same day, the `first_event_name` attribute might become a long string and the icon would not reflect the type as there might be events of different type but only one icon can be displayed.

For displaying anniversary information I'd recommend using some sort of iteration over the events list filtering on sensor.myevents.attributes.events[i].event_in == sensor.myevents.state. For example custom button-card (https://github.com/custom-cards/button-card) is flexible enough to do that.

**Comment by rdebrock91** [comment]
Oh thats why... thanks for your reply!
I came to an idea and  made 2 new sensors (event1 and event2)  and put the 2 with same birthday seperate. Works for me :) Thx anyways.
