### ISSUE TITLE
no card display

### ISSUE THREAD

**Issue by papy200** [amaximus/anniversary#5]
hello, I put the card as an example, with a birthday test on 2/09 but the card is not displayed. However I put this in the map:

Sensor.yaml

- platform: anniversary
  name: events
  multiple: true
  anniversaries:
    - event: "Schumi"
      date: "1969-09-23"
    - event: "Quentin"
      date: "1999-09-24"
      icon: mdi:cake-variant
    - event: "Chazz birthday"
      date: "2000-09-02"
      icon: mdi:cake-variant
    - event: "Frank the tank"
      date: "1998-8-18"

Card:

type: conditional
conditions:
  - entity: binary_sensor.event_in_15d
    state: 'on'

in edit mode, the card is present, with the birthday, but in normal mode, it disappears
What is the cause ?
thanks.

**Comment by amaximus** [comment]
Did you define the binary_sensor used by the conditional card?

**Comment by amaximus** [comment]
Anyway I removed the conditional card part from the README example as it caused confusion and it's unrelated to the custom integration

**Comment by papy200** [comment]
what then is the best example of a map to use? do you have a card code?

**Comment by papy200** [comment]
ok, i see.

it takes birthdays over how many days?

**Comment by amaximus** [comment]
The card code from the updated README will display you events as shown in the README images (it requires custom button card). But the UI/frontend part is out of scope of this custom integration, which runs on the backend.

**Comment by amaximus** [comment]
The state of the sensor will be the number of days till the first upcoming event.

**Comment by papy200** [comment]
ok, spotless.
Where can I change the color of the circle where the number of days is?

**Comment by amaximus** [comment]
Check out the background-color part in the notification section of custom_fields.

**Comment by papy200** [comment]
ok, thanks.
Good Job
