### ISSUE TITLE
4 anniversaries visible

### ISSUE THREAD

**Issue by stShark** [amaximus/anniversary#7]
Hi, I have not found any mistake but I would like to ask whether it would not be added to integration see the attributes of the entity next 4 anniversaries. Currently, only the first is visible. thank you

**Comment by jampez77** [comment]
I'd like to second this!

Would be nice to have access to upcoming events! I'd like to add a birthday card item to my shopping list about 14 days prior to an event occurring.

**Comment by amaximus** [comment]
Thanks for the feature request.

Recently released version 0.1.0 adds support for listing a few upcoming events in the attributes.

Please update the custom integration and get back to me with results.

**Comment by stShark** [comment]
Hi,

first of all I would like to thank you for your time editing the add-on.
Unfortunately, this will not help me much.

Currently, the attributes of an entity look like this:
[image: atributy.jpg]
I would need it to look like this:

*First event name            Kajušo narodeniny *
*First event in                                           4 *
*First event on               15. septembra 2021 *

*Anniversary                                             4 *
*Second event name               Miška meniny *
* Second event in                                     13 *
* Second event on           29. septembra 2021 *
* Second anniversary                            none*
*Third event name                 Natálka meniny *
*Third event in                                         19 *
*Third event on                     6. októbra 2021 *
*Third anniversary                                none*
*Fourth event name              Fero narodeniny *
*Fourth event in                                       23 *
*Fourth event on                  16. októbra 2021*
*Fourth anniversary                                  33*


I would like to use the individual attributes to create a Button Card. It
would look something like this:

[image: Bez názvu-1.jpg]

The color of the card would change depending on the number of days until
the anniversary.

Thank you again. Sincerely Tomas

so 11. 9. 2021 o 13:02 Atticus Maximus ***@***.***>
napísal(a):

**Comment by jampez77** [comment]
This works perfectly for me! Thanks for adding this so quickly. If this was updated to a UI config flow so restarts weren't required after additions then it would be perfect. Great work

**Comment by amaximus** [comment]
Well, I'm a yaml guy and implementing the config flow supporting adding undefined number of list entries (the list of events) is not that trivial and due to lack of time I guess I'll have to skip this.
Feel free to fork the project and add the config flow feature in the fork.
