### ISSUE TITLE
items : number of upcoming events to add to the events list attribute

### ISSUE THREAD

**Issue by papy200** [amaximus/anniversary#8]
hello,
this is to put in the sensor.yaml?

like this:

- platform: anniversary
  name: events
  multiple: true
  items: 3
  anniversaries:
    - event: "Schumi"
      date: "1969-09-23"

and he has to take back the anniversary of the next three, is that right?

**Comment by amaximus** [comment]
Yes, exactly as in your example.

**Comment by papy200** [comment]
I need to change something in my card, because a birthday on 23/09 and one on 24/9 but it only shows me the first?

**Comment by amaximus** [comment]
This project is about the integration. As long as the sensor attribute shows both events (while items is set to at least 2), the integration works ok. How do you display the data is out of scope here.

**Comment by papy200** [comment]
Sorry, I don't quite see what this is for. all my apologies ???….

another small question, where can I change the color of the circle where is the number of days remaining (me it is red) how can I put it in blue or in white?

Thanks.

**Comment by stShark** [comment]
Hi, you can use the Button card to make the card underlined according to the status of the entity as follows: 

    state:
      - value: 2
        operator: <=
        styles:
          card:
            - background-color: lightblue
      - value: 7
        operator: <=
        styles:
          card:
            - background-color: lightgreen
      - value: 14
        operator: <=
        styles:
          card:
            - background-color: indianred
      - value: 15
        operator: >=
        styles:
          card:
            - background-color: white

**Comment by amaximus** [comment]
Do you need further assistance with the number of items feature of the integration or this issue can be closed?

**Comment by robertolamm** [comment]
> Do you need further assistance with the number of items feature of the integration or this issue can be closed?

Hi amaximus, 
for sure this question is not strictly related to your big project, but I am trying to show in a lovelace card the next four "event" and "event_on" couple, but I am very confusing on how to do this :) Can you (or somebody else) kindly give me a little indication about where to look for this feature ? 
Thank you very much for your help and for your great integration.

**Comment by amaximus** [comment]
@robertolamm please see the second example in the 'Lovelace UI' section of my other repository: https://github.com/amaximus/met_alerts_hu

The idea is similar: you'll have to set 'items: 4' for the sensor and in the custom button card iterate over the list of events building the card label (event + event_on).

**Comment by robertolamm** [comment]
> @robertolamm please see the second example in the 'Lovelace UI' section of my other repository: https://github.com/amaximus/met_alerts_hu
> 
> The idea is similar: you'll have to set 'items: 4' for the sensor and in the custom button card iterate over the list of events building the card label (event + event_on).

Thanks a lot, @amaximus !!! When done, I will post here the example, for other interested people :)

**Comment by robertolamm** [comment]
_Hello,
here there is a sample code derived from the original https://github.com/amaximus/met_alerts_hu_
Hope can help.

type: conditional
conditions:
  - entity: sensor.events
    state_not: '0'
card:
  type: custom:button-card
  name: PROSSIMI EVENTI
  icon: mdi:metronome
  color: rgb(255, 128, 0)
  entity: sensor.events
  show_label: true
  show_name: true
  show_icon: true
  show_state: false
  styles:
    card:
      - height: 200px
    label:
      - font-size: 90%
      - color: rgb(255, 128, 0)
  label: |
    [[[
      var items = 4
      var label = ""
      var icolor = "rgb(255, 128, 0)"
      var event_list = states['sensor.events'].attributes.events;
      for (var k=0; k < items; k++) {
        label += `<ha-icon icon="` + event_list[k].icon +
                 `" style="width: 24px; height: 26px; color:` + icolor +
                 `; margin-bottom: 1px;">` +
                 `</ha-icon>&nbsp;` +
                 event_list[k].event_on + " - " + event_list[k].event + `<br>`;
      }
      return label;
    ]]]

![image](https://user-images.githubusercontent.com/87273127/134900494-574d87d3-7b90-4f03-9afc-7cf9da862dc1.png)

**Comment by amaximus** [comment]
Great. I'm glad you could sorted it out.
