### ISSUE TITLE
feature request:   Ability to define a type field

### ISSUE THREAD

**Issue by jane-t** [amaximus/anniversary#9]
Thank you very much for this useful integration. 

I currently have Birthdays and Anniversaries in the set up and use a different icon for each, however this is not included in the events list, so I can not include when outputting the list of upcoming events using a template.

Ideally I would like to be able to define a type field to use to condition the output easily for notifications on my morning schedule like

Nick's 52nd birthday in 4 days,  Nick and Jeannnette's 25th wedding anniversary in 39 days.

and if possible include the type and the icon in the events list on the sensor attributes.

**Comment by amaximus** [comment]
New release (0.2.0) pushed recently adds support for event types in attribute.

Please upgrade the integration and get back to me with results.

**Comment by jane-t** [comment]
Thanks that works well.  I uses the following script to produce a string for Alexa to read out during the morning routine.

`{% for state in state_attr('sensor.events','events')|list %}
{% set n = state.anniversary %}
{% set e = n |string %}
{% set e = e [-1]%}
{% if n in [11,12,13,14,15,16,17,18,19] %}{% set ex = 'th' %}
{% elif e == '1' %}{% set ex = 'st' %}
{% elif e == '2' %}{% set ex = 'nd' %}
{% elif e == '3' %}{% set ex = 'rd' %}
{% else %}{% set ex = 'th' %}{% endif %}
{{ state.event }}'s {{state.anniversary}}{{ex}} {{state.type}} in {{ state.event_in }} days,
{% endfor %}`

**Comment by amaximus** [comment]
Thanks for confirmation.
